# Generated by Django 5.0.6 on 2024-06-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='task',
            name='image_url',
            field=models.URLField(default='https://images.nplod.ru/gen_images_3/pbL0X0WmoV99X8lL7MSp2ZoZ0E3DEnaH_sm.jpg'),
        ),
    ]
